### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by yurrriq** [yurrriq/pynchon#2]
#### REPL:
```lfe
> (include-lib "include/swiss-arrows.lfe")
loaded-arrows
> (-<> 0 (* <> 5) (list 1 2 <> 3 4))
(1 2 0 3 4)
```

#### Test:
```lfe
(deftest why-does-this-fail?
  (is-equal (-<> 0
                 (* <> 5)
                 (list 1 2 <> 3 4))
            '(1 2 0 3 4)))
```
```bash
$ make test
/usr/local/bin/rebar compile
==> lfe (compile)
==> lutil (compile)
==> color (compile)
==> ltest (compile)
==> kla (compile)
==> clj (compile)
==> swiss-arrows (compile)
/usr/local/bin/lfetool tests unit
Removing old tests ...
rm -rf ./.eunit
mkdir: created directory ./.eunit
Compiling tests ...
./test/swiss-arrows-tests.lfe:13: error expanding (-<>* (list 1 2 <> 3 4) (-<> 0 (* <> 5)) 'first)
Successfully compiled test modules.


------------------
Running unit tests ...
------------------

======================== EUnit ========================
swiss-arrows-tests: diamond-test ...[ok]
=======================================================
  Test passed.
```

For now, [this test][1] is commented out...

[1]: https://github.com/yurrriq/swiss-arrows/blob/1d79213740a30a1b386a63b594f54161e17432de/test/swiss-arrows-tests.lfe#L12-L15

**Comment by oubiwann** [comment]
So, the first thing I wanted to see was why ``(include-lib ...)`` wasn't working for this project. I did  this which showed that your ``ERL_LIBS`` isn't set up correctly:

```
$ ./deps/lfe/bin/lfe
...
LFE Shell V7.0 (abort with ^G)
> (application:load 'swiss-arrows)
#(error #("no such file or directory" "swiss-arrows.app"))
```

This is why I use the standard lfetool ``Makefile`` (and includes) in projects: to set up deps and current project so that app files are found. You can do this "manually" with the following:

```cl
$ ERL_LIBS=`lfetool info erllibs` ./deps/lfe/bin/lfe
...
LFE Shell V7.0 (abort with ^G)
> (application:load 'swiss-arrows)
ok
```

The reason that this is important is that ``(include-lib ...)`` won't work if Erlang can't find the given project's ``ebin``/``include`` dirs; adding the project and it's deps to ``ERL_LIBS`` allows Erlang to find these files.

However, with that done, attempting to include the macros still fails:

```cl
> (include-lib "swiss-arrows/include/swiss-arrows.lfe")
1: error expanding (include-lib "swiss-arrows/include/swiss-arrows.lfe")
error
```

When expanding, we get a little more info:

```cl
> (macroexpand '(include-lib "swiss-arrows/include/swiss-arrows.lfe") $ENV)
exception error: #(expand_macro
                   (include-lib "swiss-arrows/include/swiss-arrows.lfe")
                   #(badarg
                     (#(lfe_macro_include lib 3 (#(...) ...))
                      #(lfe_macro exp_predef_macro 3 (#(...) ...))
                      #(lfe_macro expand_expr 2 (...))
                      #(lfe_lib macroexpand 2 ...)
                      #(lfe_shell eval_form_1 ...)
                      #(lfe_shell ...)
                      #(...) ...)))
  in lfe_macro:exp_predef_macro/3 (src/lfe_macro.erl, line 559)
  in lfe_macro:expand_expr/2 (src/lfe_macro.erl, line 74)
  in lfe_lib:macroexpand/2 (src/lfe_lib.erl, line 314)
```

This is the point at which I would call to @rvirding for help, since I'm not sure why there's a ``badarg`` error here, but not when ``(include-file ...)`` is used.

Using include-file works just fine, as you discovered in your test module when you commented out the ``(include-lib ...)``:

```cl
> (include-file "include/swiss-arrows.lfe")
loaded-arrows
```

And expanding that like we did the other one shows everything in order, as you would expect.

I actually *have* run across this problem before, but for the life of me, I can't remember in which library and if I ever came up with a solution. If I did, it probably took days. Maybe @rvirding can help us short-cut that painful process ...

**Comment by rvirding** [comment]
IIRC you can't use a '-' in the application name as it seems to screw up
the when it is parsing the application directory name to handle versions.
I.e when you search for the application 'foo' and it finds it in the
directory 'foo-3.45.2'. It is a shame as it makes the application names
less lispy.

Robert

**Comment by oubiwann** [comment]
Ah, that's sounding very familiar ...

[searching the mail list ...]

Bingo! Good memory, Robert:
 * https://groups.google.com/d/msg/lisp-flavoured-erlang/oP0GaVFeVyY/-lDkpwS-DKQJ

That's exactly what this is. 

@yurrriq Note that when changing the application name, you will also need to change the name of the directory of the cloned repo, since when using ``ERL_LIBS``, the project's directory name has to match the application name when finding the ``ebin`` and ``include`` dirs.

When I've had to do this in the past, I've either changed the name of the project, or given explicit setup steps with warnings and caveats that they need to do *exactly* as instructed, or things will break, e.g.:

```
$ git clone https://github.com/yurrriq/swiss-arrows swissarrows
```

If you *did* want to rename the project, ``pynchon`` would be a great name :-) (Or you could pun with ``pynchorn`` ... I'm so bad, I know ...)

**Comment by yurrriq** [comment]
Aha! Thanks for the insight. :+1: for changing the name (and files accordingly) to Pynchon.

What about the failing test itself? Is it related to this issue or something else? It seems odd that the first test passes but the second doesn't...

**Comment by yurrriq** [comment]
Compilation seems to specifically fail when I try to include tests of the form:

```clojure
(-<> 6 (* 7 <>))
```

That is, when a sub-form<sup>1</sup> contains `<>`. That code runs fine in a REPL and returns `42`, but if I try to add it as a test:

```clojure
(deftest forty-two
  (is-equal 42 (-<> 6 (* 7 <>))))
```

```
$ lfetool tests unit
...
./test/include-pynchon-tests.lfe:36: error expanding (-<>* (* 7 <>) 6 'first)
...
```

I've [added some more failing tests][1] (that work in a REPL) as well as [some commentary][2] on my potentially erroneous code.


<sup>1</sup> Is *sub-form* the proper parlance?

[1]: https://github.com/yurrriq/pynchon/commit/8841af085f07187d409fb1042f1b8c56a0652f05
[2]: https://github.com/yurrriq/pynchon/commit/02ad5d5167ce24f01eea571437112fbf8aa49f86

**Comment by oubiwann** [comment]
What happens if you try this:

```cl
(deftest forty-two
  (let ((first-part (* 7 <>)))
    (is-equal 42 (-<> 6 first-part))))
```

(Not meant to be a work-around/solution ... just trying to peer into the issue more.)

**Comment by rvirding** [comment]
Try compiling it with `(c swiss-arrows '(return report))`. This will return a stacktrace (and print the error message) which might help in determining what went wrong.

**Comment by yurrriq** [comment]
@oubiwann, that definitely shouldn't work since the `<>` is outside of the macro call at that point. I'll try `'(return report)`.

**Comment by yurrriq** [comment]
`(c "test/include-pynchon-tests.lfe" '(return report))` helped me learn that `defun`s in a file like [include/pynchon.lfe][1] don't play nice. (I got various descriptive and helpful "undefined function" errors)

[1]: https://github.com/yurrriq/pynchon/blob/c42bcdec9be80c524f13203861becc368c1192a4/include/pynchon.lfe

**Comment by yurrriq** [comment]
Note to self: `eval-when-compile`
